# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'neighborhood watch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for neighborhood watch
    pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'

  target 'neighborhood watchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'neighborhood watchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
